export const noteState = {
  READING: "READING",
  EDITING: "EDITING"
}

export const name = {
  DELETE: "DELETE",
  DELETE_FOREVER: "DELETE_FOREVER",
  EDIT: "EDIT",
  RESTORE: "RESTORE",
  UNDO: "UNDO",
  ARCHIVE: "ARCHIVE",
  UNARCHIVE: "UNARCHIVE"
}